# Generated by Django 4.2.5 on 2023-09-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poesias', '0002_poesia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(default='PIX', max_length=100)),
                ('data_venda', models.DateField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poesias.livro')),
                ('poesia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poesias.poesia')),
            ],
        ),
    ]
